### ISSUE TITLE
Consider integrating RoTTA

### ISSUE THREAD

**Issue by DYW77** [LINs-lab/ttab#11]
Hello, I noticed a new test-time adaptation method called Robust Test-Time Adaptation (RoTTA) proposed in this paper
https://arxiv.org/abs/2303.13899.
According to the paper, RoTTA achieves state-of-the-art performance and outperforms some existing methods like TENT, CoTTA, NOTE, etc.

I tried integrating RoTTA into the codebase myself. However, when I tested it, the accuracy rate I got was much lower than reported in the original RoTTA paper . I tried to debug it but couldn't get the accuracy up. I wonder if you have considered integrating RoTTA? As the original authors of the codebase, you may have better insights on how to properly integrate RoTTA.

Please let me know if you would be interested in integrating RoTTA. I'm happy to provide more details on the issues I encountered. I think RoTTA could further improve the codebase's adaptation capabilities.

Thank you for your attention! Please let me know if you need any other information from me.

**Comment by YuejiangLIU** [comment]
Thanks for the suggestion! IIUC, the paper proposed both a new setting (PTTA) and a new method (RoTTA). Leaving aside their proposed method, did you integrate the PTTA setting and obtain sensible results from other methods in that setting?

**Comment by DYW77** [comment]
Thanks for your reply. The original RoTTA code only contains the RoTTA method, so if I want to obtain results from other methods in that setting, I need to validate other methods additionally. But I'll try to validate PTTA first before looking at RoTTA. I'll follow up once I have PTTA results.

**Comment by DYW77** [comment]
Hello,Here are the issues and steps I encountered:

Following the description in the RoTTA paper, I implemented the RoTTA method in our codebase, adhering to their proposed setting.

I used the cifar10_c dataset and performed tests in each .npy, recording the corresponding accuracy rates.
However, the obtained accuracy rates were consistently lower by approximately 10% compared to the reported results in the paper.(Through testing, the original RoTTA code achieved an average accuracy of approximately 75% on the cifar10_c dataset.)

I have uploaded the modified RoTTA code to the repository https://github.com/DYW77/RoTTA-in-TTAB. 

I am highly interested in integrating the RoTTA method into our codebase, as I believe it can enhance our adaptation capabilities. However, I am currently unable to resolve this accuracy issue.

Could you please provide any suggestions or guidance to help me address this problem? I am willing to provide additional information about our codebase and environment setup to facilitate a better understanding of the situation.

Thank you for your attention, and I look forward to your response.

**Comment by MarcellusZhao** [comment]
Thanks for your message! We are also very interested in integrating RoTTA method into our codebase!

But we are a bit busy recently, so I am not sure when I have time to check this repository, probably two weeks later. I will get back to you soon once I find something. Stay tuned :)

Again, thanks for your interest in our work and contribution!
