### ISSUE TITLE
Is there guides to analysize the results for run_exps.py ?

### ISSUE THREAD

**Issue by Lily-Le** [LINs-lab/ttab#14]
Thanks again for your marvelous job.  After running run_exps.py,  there're lots of json files in ./logs folder. Are there written tools to analysize the results? Eg. to get the mean acc over all the corruptions for cifar10c? 

Also, after running run_exps.py, there're lots of tmux sessions with only one window. It bothers to kill all the related sessions afterwards when there're other tmux sesions related to other experiments.  Is there anything wrong with my usage of the code? Looking forward to a more detailed doc for all the useful tools in the repository.

Thanks very much.

**Comment by MarcellusZhao** [comment]
Sorry for late reply.

> Are there written tools to analysize the results? Eg. to get the mean acc over all the corruptions for cifar10c?

Yes and we have uploaded a basic version of notebooks for further analyse. Please check it out and hope it can help to accerelate your research :) More details can be found in [this section](https://github.com/LINs-lab/ttab#using-the-example-scripts).

> It bothers to kill all the related sessions afterwards when there're other tmux sesions related to other experiments. Is there anything wrong with my usage of the code?

It's a good question. In the server we worked with, we apply for a computational node every time for one particular experiment and we have multiple nodes working simultaneously and independently. Thus, we did not come across the trouble you mentioned and did not spend time creating corresponding tools for it. To fix it, probably checking tmux documentation may help?

**Comment by Lily-Le** [comment]
Thanks a lot!  :D
