### ISSUE TITLE
Reproducing Figure 3 results in paper

### ISSUE THREAD

**Issue by wonjeongchoi** [LINs-lab/ttab#15]
Dear authors,
thank you for your great works!
Now, i'm trying to reproduce some results in your paper under the TTAB benchmark.

But, the results which i have got are not consistent with those in your paper..

Especially, the figure below is our reproduced version of Figure 3(a) with lr=0.01 (green curve in the paper).
![fig3_repr](https://github.com/LINs-lab/ttab/assets/80087614/a881cb52-fd7f-45ad-be9b-2a2252bd027c)

You can see that the result is quite different to the figure 3(a)..
In the experiment, i use following configurations based on your paper.

ckpt_path:"./pretrain/ckpt/resnet26_bn_ssh_cifar10.pth" **(this ckpt is what you provided in google drive)**
seed:2022
model_adaptation_method:"shot"
model_selection_method:"last_iterate"
data_names:"cifar10_c_deterministic-gaussian_noise-5"
lr:0.01
n_train_steps:1
(The others are same as the base setting in TTAB implementations)

Can you provide more details about the configurations for figure 3(a) and 3(b)?

Thank you!

**Comment by MarcellusZhao** [comment]
Hi, thanks for proposing this important question!

This problem arises due to the setup, which we forgot to mention in the paper. The results we show at Figure 3 are based on ResNet-20 pretrained on CIFAR-10, and ResNet-26 is used to benchmark table results following prior work's setup. That's why the figure you show has a higher accuracy (~63%) at `batch_index=1`, while it's around 40% in the paper.

**Comment by MarcellusZhao** [comment]
I uploaded the logs we used in Figure 3a in [google drive](https://drive.google.com/drive/folders/1yhhzbrf4STEaDxdQHwyXNwE2r63QeJcC?usp=sharing). Hope it helps!

**Comment by MarcellusZhao** [comment]
Setups for figure 3b [here](https://drive.google.com/drive/folders/1Zpr3P4wqksghIOIJsil7TMmQGO9zmBrE?usp=sharing)

**Comment by MarcellusZhao** [comment]
You can also find the checkpoint for ResNet-20 on CIFAR10 in google drive, where you downloaded the one for ResNet-26.

**Comment by wonjeongchoi** [comment]
Thank you for your kind and detailed response!!

I'll let you know after reproducing the results once again.

**Comment by wonjeongchoi** [comment]
Hi, I tried reproducing once again but it still shows weird results like below.

![image](https://github.com/LINs-lab/ttab/assets/80087614/d46e1375-8cb1-4f77-b0c7-e1cbe00a8431)


As you mentioned, i used checkpoint for ResNet-20 on CIFAR10 (what you provided in google drive).
Also, following the argument file you provided, I changed argument 'threshold_shot' to 0.8 (in ttab/config/algorithms.py) because it was set to 0.9 as base setting. 
So, the differences of configuration between yours and mine are following. (left: yours, right: mine)
![image](https://github.com/LINs-lab/ttab/assets/80087614/56ffeedf-9973-4aa4-bce3-981c0f339d35)


I can't understand why the results are still different in spite of almost the same configurations.
Is there any change of algorithm (shot) specific arguments such as optimizer, auxiliary_batch_size, threshold_shot, ent_par, cls_par, offline_nepoch?
I used following settings to reproduce my result.
"shot": {
        "optimizer": "SGD",  # Adam for officehome
        "auxiliary_batch_size": 32,
        "threshold_shot": 0.8, # originally 0.9, confidence threshold for online shot.
        "ent_par": 1.0,
        "cls_par": 0.3,  # 0.1 for officehome.
        "offline_nepoch": 30, # originally 10
    },


Thank you!

**Comment by MarcellusZhao** [comment]
Hi, @wonjeongchoi 

I tested it on my pc using the current `ttab`codebase and get the following result on `lr=0.01` and `nstep=1` (curve is smoothed)
![cifar10c_lr0 01_nstep1](https://github.com/LINs-lab/ttab/assets/50657356/bc04317e-b368-4800-9366-d2ab355c6e6b)
The final performance is close to what we reported in the paper, though still having some small difference on the curve it self. I think the conclusion from the result is well aligned with our paper. As for the difference, we polished the codebase after submission and probably some modification caused this trouble, while the reason behind this is still unknown to us.

Thanks for your contribution on helping us improving this repo.

**Comment by MarcellusZhao** [comment]
The difference in python environment (e.g., the version of packages) and hardware may also partly attribute to this phenomenon.

**Comment by wonjeongchoi** [comment]
Thank you so much!!

I tried multiple times after resetting environment and ttab codebase but my results still show fluctuating curves :(
As you mentioned, I guess the reason of different reproduced results is due to the environment settings.

Can you provide some following information about the environment/dataset you use?
- python version
- version of packages (with `conda list` command or whatever)
- seed
- c.f. Did you plot the results based on the **accuracy_top1** from the output **log-1.json** file?

Thank you!

**Comment by MarcellusZhao** [comment]
Hi @wonjeongchoi ,

Did you try to smooth the performance curve? Fluctuation happens and it's not something unusual. This is the pre-smoothed curve I obtained before,
![output](https://github.com/LINs-lab/ttab/assets/50657356/16cc01c4-5e38-4d97-9d9f-cb2fedf4acdf)

And the results in the paper is also smoothed.

**Comment by wonjeongchoi** [comment]
Ah, I got it.

Now, I get a result below after smoothing the fluctuated curve.
Here, I use Exponential Moving Average (with weight 0.9) to smooth our curve following [implementations](https://stackoverflow.com/a/49357445/985012) i found.

![image](https://github.com/LINs-lab/ttab/assets/80087614/646d88c4-4d6f-49d1-bb86-62c1cbe9230c)

Could you please let me know which smoothing method was used in the paper?

Thank you.

**Comment by MarcellusZhao** [comment]
Please check `notebooks/example.ipynb`, we provide a basic tool to analyze extracted results from logs. There is an argument controlling the smoothing behaviour.

**Comment by wonjeongchoi** [comment]
Thank you for your kind responses!!

It's really helpful to me. Then, i will close this issue.

Thank you again!
