### ISSUE TITLE
Could you add ImageNet support to pre-trained model code ssl_pretrain.py?

### ISSUE THREAD

**Issue by DYW77** [LINs-lab/ttab#16]
Dear authors, I'm using your pre-trained model code ssl_pretrain.py and hope to apply it on ImageNet dataset. However, I noticed currently the code does not support ImageNet dataset.Would it be possible to add the support? Please let me know if you have any plans for this. Thanks!

**Comment by MarcellusZhao** [comment]
Sorry for the late reply. We don't have a plan to support the pretraining on the ImageNet dataset, as the cost will be huge and there are already some well-established code repositories and pre-trained models out there.
