### ISSUE TITLE
Different dataset sizes cause list out of range error on OfficeHome experiment

### ISSUE THREAD

**Issue by mingxilei** [LINs-lab/ttab#17]
The error is noticed when adapting models from source domain realworld to target domain art. Domain art has smaller size of data.

In your source code (ttab.loads.datasets.dataset.py line 332), the method to load a target domain is to load the source domain first, then replace the data and targets (ttab.loads.datasets.dataset_shift.py). The data_size and indices are not updated, so len(dataset.data) != len(dataset). The iterator still uses larger indices of realworld to get items so it cause that error.

**Comment by MarcellusZhao** [comment]
Thank you for identifying this issue. This issue has been fixed! So I'll close this ticket.
