### ISSUE TITLE
What is the group_norm_num_group for resnet26_gn ?

### ISSUE THREAD

**Issue by Lily-Le** [LINs-lab/ttab#19]
What is the group_norm_num_group for resnet26_gn ? Can you provide the pretrain command line for gn model in readme? Thanks for the marvelous job!

**Comment by MarcellusZhao** [comment]
Hi,

`group_norm_num_group ` refers the number of groups to separate the channels into, and the default value we used is 8. It is equivalent to the variable `group_norm` in `pretrain/ssl_pretrain.py`. I've updated the README.

Thanks for your interests in our work!
