### ISSUE TITLE
Dear authors,  I have requests on several things I already sent an email to author.

### ISSUE THREAD

**Issue by AAAI-2025** [LINs-lab/ttab#8]
Dear authors,
I have requests on several things.
There are two "--inter_domain" in the code: HeterogeneousNoMixture, CrossMixture. CrossMiture shuffles data across domains; HeterogeneousNoMixture constructs label shfit (non-iid) over domains. 
I want to mix the multi domains first, then construct label shift.
So I do the following two steps:
1. data =  self._intra_shuffle_dataset(
                self._merge_datasets(test_datasets), random_seed=random_seed)
2. data2 = self._intra_non_iid_shift(
                        dataset=data,
                        non_iid_pattern=test_case.inter_domain.non_iid_pattern,
                        non_iid_ness=test_case.inter_domain.non_iid_ness,
                        random_seed=random_seed,
                    )
      return data2;
However, after  step 1, step 2 cannot success (the label shift fails to be constructed).
Could you please help me solve this issue? Or add some annotation to "  _intra_non_iid_shift" .

**Comment by MarcellusZhao** [comment]
Hello,

Could you provide more details, such as reported error message, parameters (e.,g., `data_name`)? I will try to add some comments to the code recently.

**Comment by MarcellusZhao** [comment]
Hello, do you still need help about this issue? if not, I would like to close this issue.

**Comment by AAAI-2025** [comment]
Hello, thanks for your reply. We have solved this issue.  It can be closed now. 
Thanks again.
