### ISSUE TITLE
The CoTTA code is not working properly.

### ISSUE THREAD

**Issue by ultimatemagic79** [LINs-lab/ttab#9]
Thank you for creating a great benchmark.

I have one question on the implementation.

`python3 run_exp.py --model_adaptation_method cotta`

When I try to use CoTTA with this parameter, I get the following error.

`TypeError: __init__() got an unexpected keyword argument 'resample'`

Line 125 in cotta.py,
```
transforms.RandomAffine(
    degrees=[-8, 8] if soft else [-15, 15],
    translate=(1 / 16, 1 / 16),
    scale=(0.95, 1.05) if soft else (0.9, 1.1),
    shear=None,
    resample=PIL.Image.BILINEAR,
    fillcolor=None,
),
```
By looking around, the official pytorch [website](https://pytorch.org/vision/main/generated/torchvision.transforms.RandomAffine.html#torchvision.transforms.RandomAffine) says 
```
CLASStorchvision.transforms.RandomAffine(degrees, translate=None, scale=None, shear=None, interpolation=InterpolationMode.NEAREST, fill=0, center=None)
```
and there is no `resample` argument.

Thanks in advance.

**Comment by YuejiangLIU** [comment]
Thank you, @ultimatemagic79, for bringing this up. It looks like a Pytorch version issue. We will fix it and get back soon. 
In the meantime, you may resolve the issue locally by replacing the `resample` arg with `interpolation`, as per [Pytorch docs](https://pytorch.org/vision/0.13/generated/torchvision.transforms.RandomAffine.html#torchvision.transforms.RandomAffine).

**Comment by ultimatemagic79** [comment]
Thanks all for the lighting fast response. I'll make some changes locally and see if there are any problems.

**Comment by MarcellusZhao** [comment]
Hello, does our suggestion solve your problems? If it does, I would like to close this issue.

**Comment by ultimatemagic79** [comment]
Sorry for the delay in commenting ... I will close this issue now that it has been resolved
